### ISSUE TITLE
multi-module にする

### ISSUE THREAD

**Issue by kokoichi206** [android-project-46group/android#83]
現状、以下の課題があり開発に速度が出なくなっている。

- Compose の Preview に時間がかかる
- strings など共通ファイルの規模がでかくなっている
  - どこを見たらいいか探すのがしんどい

これらを解消したく、multi-module project へと変更してみる。

**Comment by kokoichi206** [comment]
分けすぎてもしんどいっぽいけど、それは1回やってみてからかな

**Comment by kokoichi206** [comment]
## なぜかぬるぽ

これはなんだろ

```
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <this>
  at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Unknown Source:2)
  at jp.mydns.kokoichi0206.domain.usecase.get_members.GetMembersUseCase$invoke$1.invokeSuspend(GetMembersUseCase.kt:32)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

下の `members.map`（テスト用のログ `members.toString()`）で出てるぽいんだけど、Non-null object なんだよなぁ。。。

```kotlin
class GetMembersUseCase @Inject constructor(
    private val repository: SakamichiRepository,
) {
    // ここで Members -> List<Member> に変えている
    operator fun invoke(groupName: String): Flow<Resource<List<Member>>> = flow {
        Log.d("hoge", repository.toString())
        try {
            emit(Resource.Loading())
            Log.d("hoge", repository.getMembers(groupName).members.toString())
            val members = repository.getMembers(groupName).members.map { it.toMember() }
```

## 原因

API_KEY が間違っている時このエラーになってるっぽい

- 今の値: `"buildConfig.API_KEY"`

**Comment by kokoichi206** [comment]
## Links

- [マルチモジュール アプリでの Hilt](https://developer.android.com/training/dependency-injection/hilt-multi-module?hl=ja)
- [hilt を使用した依存関係の注入](https://developer.android.com/training/dependency-injection/hilt-android?hl=ja)

**Comment by kokoichi206** [comment]
`Preview` を行う際に重要となる次の 3 つの動作について、それぞれ変更前と後で時間を比較しました。

- 1. Build Refresh
  - Preview の内容を変更した際に変更を反映させます。
  - ![](img/build_refresh.png)
- 2. Start Interactive Mode
  - `Interactive Mode`（Preview Mode でタッチ操作可能なモード）を有効にする
  - ![](img/interactive_mode.png)
- 3. Stop Interactive Mode
  - `Interactive Mode` を止める

それぞれ 3 回ずつ測定し平均を求めております。

| 変更前 | | マルチモジュール |
| :---: | :---: | :---: |
| 12.1 | 1.Build | 7.5 |
| 9.5 | 2.Start<br/>画面1 | 2.6 |
| 11.2 | 2.Start<br/>画面2 | 2.9 |
| 8.7 | 3.Stop<br/>画面1 | 3.2 |
| 9.3 | 3.Stop<br/>画面2 | 2.7 |
