### ISSUE TITLE
API_KEY が有効でない時ぬるぽが発生してアプリがクラッシュする

### ISSUE THREAD

**Issue by kokoichi206** [android-project-46group/android#84]
https://github.com/android-project-46group/android/issues/83#issuecomment-1302036861

- 発生する API
  - members
  - positions
- 発生しない API
  - blog (403)

**Comment by kokoichi206** [comment]
## members

### エラー発生箇所

以下の `map` の部分。

```kotlin
class GetMembersUseCase @Inject constructor(
    ...
) {
    ...

    operator fun invoke(...
        ...
        val members = repository.getMembers(groupName).members.map { it.toMember() }
```

Retrofit 設定部分

```kotlin
@Module
@InstallIn(SingletonComponent::class)
object DataModule {

    // API
    @Provides
    @Singleton
    fun provideSakamichiApi(): SakamichiApi {
        val okHttpClient = OkHttpClient.Builder()
            // サーバー側の設定か、なぜか指定が必要！
            .connectTimeout(777, TimeUnit.MILLISECONDS)
            .addInterceptor(AddHeaderInterceptor())
            .addInterceptor(LoggingInterceptor())
            .addInterceptor(RetryInterceptor())
            .build()
        return Retrofit.Builder()
            .baseUrl(Constants.BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(SakamichiApi::class.java)
    }
    ...
}

/**
 * Interface for accessing the APIs with Retrofit.
 */
interface SakamichiApi {

    @GET("api/v1/members")
    suspend fun getMembers(
        @Query("gn") groupName: String,
        @Query("key") apiKey: String = "",
    ): MembersDto
    ...
}
```

### エラーメッセージ

いわゆるぬるぽ。

```
Process: jp.mydns.kokoichi0206.sakamichiapp, PID: 23962
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter <this>
     at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Unknown Source:2)
     at jp.mydns.kokoichi0206.domain.usecase.get_members.GetMembersUseCase$invoke$1.invokeSuspend(GetMembersUseCase.kt:66)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

### いつから？

[Usecase 実装初期](https://github.com/android-project-46group/android/tree/api_key_test)から発生している症状っぽい。

できればテストで拾いたかった（？）

**Comment by kokoichi206** [comment]
## 原因は何か

API レスポンスの JSON を Gson を使ってよしなに返却 Data class（MembersDto）に変換してくれているが、そこの内容が Null ということである。

インターネットが繋がってない時は、`IOException` が retrofit から上がってきて、usecase で補足できている

```kotlin
operator fun invoke(groupName: String): Flow<jp.mydns.kokoichi0206.common.Resource<List<Blog>>> = flow {
    try {
        emit(jp.mydns.kokoichi0206.common.Resource.Loading())
        val members = repository.getBlogs(groupName).blogs.map { it.toBlog() }
        emit(jp.mydns.kokoichi0206.common.Resource.Success(members))
    } catch (e: HttpException) {
        emit(jp.mydns.kokoichi0206.common.Resource.Error(e.localizedMessage ?: "An unexpected error occurred."))
    } catch (e: IOException) {
        // =========  ここに入る  ==========
        emit(jp.mydns.kokoichi0206.common.Resource.Error("Couldn't reach server. Check your network connection"))
    }
}
```

なぜ `API_KEY` が間違ってる時も例外として捕捉されないのか。

**Comment by kokoichi206** [comment]
## API

API で `API_KEY` が間違っている時、[ステータスコード 200 が返ってきてた。。。](https://kokoichi0206.mydns.jp/api/v1/members?gn=hinatazaka&key=dummy_key)

おそらくこれが原因

1. 200 を見て成功と判断
2. Json から返却の型にパースを試みる
3. 結果失敗 → そのまま Null で返ってくる

型で NonNull に指定しているんだから、そこで拾ってほしさあるよね。。。

Gson 側か Retrofit 側に問題がある。

### TODO

- api 側の回収
- どちらにせよ、parse が失敗した時に Exception を投げるか処理が進まないようにしたい。
  - （Retrofit, Gson にはなさそう、自作？）
  - [retrofit converter はいっぱい他にもあるみたい、何個か試す](https://github.com/square/retrofit/tree/master/retrofit-converters)

**Comment by kokoichi206** [comment]
## Retrofit でサポートしている converter の調査

2022/11/22 現在、[サポートしている converter](https://github.com/square/retrofit/tree/master/retrofit-converters)

<img width="852" alt="Screenshot 2022-11-22 at 20 11 32" src="https://user-images.githubusercontent.com/52474650/203299851-1ef9fbdd-7838-462b-a6e0-2abc7be0d3b9.png">

### Moshi

[failOnUnknown](https://square.github.io/moshi/1.x/moshi/moshi/com.squareup.moshi/-json-adapter/fail-on-unknown.html) として、不明なパラメータが来たときにエラーを吐かせることが[できそう](https://github.com/square/retrofit/blob/master/retrofit-converters/moshi/src/main/java/retrofit2/converter/moshi/MoshiConverterFactory.java)。
（ただ、正常のパラメーターを送った時にもエラーが出たので謎。。。）

```
Process: jp.mydns.kokoichi0206.sakamichiapp, PID: 9798
    com.squareup.moshi.JsonDataException: Cannot skip unexpected NAME at $.members[0].
     at com.squareup.moshi.JsonUtf8Reader.skipName(JsonUtf8Reader.java:589)
```

→ 以下のように変更したら解決した（[Moshi KotlinJsonAdapterFactory cannot parse Json after enabled minify](https://stackoverflow.com/questions/57034937/moshi-kotlinjsonadapterfactory-cannot-parse-json-after-enabled-minify)）

`@Json` ではなく、`@field:Json` とする。

```kotlin
import com.squareup.moshi.Json

data class MemberDto(
    val birthday: String,
    @field:Json(name = "blog_url")
    val blogUrl: String,
    @field:Json(name = "blood_type")
    ...
```

### Gson

[何も設定できるものはなさそう](https://github.com/square/retrofit/blob/master/retrofit-converters/gson/src/main/java/retrofit2/converter/gson/GsonConverterFactory.java)

### Jackson

確かではないが、[多分できなさそう](https://github.com/square/retrofit/blob/master/retrofit-converters/jackson/src/main/java/retrofit2/converter/jackson/JacksonConverterFactory.java)

### guava

ない

### jaxb

きつそう

**Comment by kokoichi206** [comment]
## 方針

どのように Response Body のデコードが失敗した時のぬるぽを防ぐか。

1. Moshi を使って、デコード失敗したら例外を投げるようにし、それを捕捉する
    * メリット
      * 該当の失敗のみを捕捉できる
    * デメリット
      * Gson から Moshi に変えるのでライブラリを変えることになる
2. 返却 object を Nullable にする
    * メリット
      * 変更が簡単
    * デメリット
      * 容易に Nullble にすると Kotlin の良さが消える

サーバー側の値のせいで Null になることはない部分であり、Null になるとしたら何かがおかしい。
そのため Nullable にして隠蔽するのは良くない。
→ 1 の方針で進める
